[package]
name = "rust-just-rates"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctrlc = "3.2.4"
log = "0.4.17"
simple-websockets = "*"

[dev-dependencies]
rstest = "0.16.0"
